---
title: "Google Vis examples"
author: "Kurt Fitz"
date: "29/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r dependson="gv"}
suppressPackageStartupMessages(library(googleVis))

M <- gvisMotionChart(Fruits, "Fruit", "Year",
                     options=list(width=600, height=400))

## prints just the html
print(M, "chart")

## opens in new web page
plot(M)

## Combining multiple plots together

```


```{r multiplot, dependson="gv", results="asis", cache=TRUE}

## Combining multiple plots

G <- gvisGeoChart(Exports, "Country", "Profit", options=list(width=200, height=100))
T1 <- gvisTable(Exports, options=list(width=200, height=270))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=400, height=370))
GT <- gvisMerge(G,T1, horizontal = FALSE)
GTM <- gvisMerge(GT, M, horizontal = TRUE, tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")

```

```{r,dependson="multiplot", results="asis", cache=TRUE}
print(GTM, "chart")

```


